=== pilipeikoko/XmlParser/src/main/resources/data/oldCards.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified"
        xmlns:tns="https://github.com/pilipeikoko/XmlParser"
        targetNamespace="https://github.com/pilipeikoko/XmlParser">

    <element name="old-cards">
        <complexType>
            <sequence>
                <element ref="tns:postcard" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Postcard">
        <sequence>
            <element name="theme" type="string"/>
            <element name="is-sent" type="boolean"/>
            <element name="country" type="tns:Country" minOccurs="1" maxOccurs="1"/>
            <element name="release-date" type="date"/>
            <element name="author" type="string" minOccurs="0" maxOccurs="1"/>
            <element name="valuation" type="tns:Valuation" minOccurs="1" maxOccurs="1"/>
        </sequence>
        <attribute name="postcard-id" type="tns:Postcard-id" use="required"/>
        <attribute name="postcard-website" type="tns:Website" use="optional" default="defaultwebsite.com"/>
    </complexType>

    <complexType name="Congratulatory-postcard">
        <complexContent>
            <extension base="tns:Postcard">
                <sequence>
                    <element name="holiday" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Advertising-postcard">
        <complexContent>
            <extension base="tns:Postcard">
                <sequence>
                    <element name="company" type="string"/>
                    <element name="expiration-date" type="date"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>


    <simpleType name="Postcard-id">
        <restriction base="ID">
            <pattern value="\w{1,20}"/>
        </restriction>
    </simpleType>


    <simpleType name="Website">
        <restriction base="string">
            <pattern value="(https?://)?([\w\d]+\.)?[\w\d]+\.\w+/?.+"/>
        </restriction>
    </simpleType>

    <simpleType name="Country">
        <restriction base="string">
            <enumeration value="LATVIA"/>
            <enumeration value="BELARUS"/>
            <enumeration value="LITHUANIA"/>
            <enumeration value="RUSSIA"/>
            <enumeration value="POLAND"/>
            <enumeration value="UKRAIN"/>
        </restriction>
    </simpleType>

    <simpleType name="Valuation">
        <restriction base="string">
            <enumeration value="HISTORICAL"/>
            <enumeration value="COLLECTIBLE"/>
            <enumeration value="THEMATIC"/>
        </restriction>
    </simpleType>


    <element name="postcard" type="tns:Postcard"/>
    <element name="congratulatory-postcard" type="tns:Congratulatory-postcard" substitutionGroup="tns:postcard"/>
    <element name="advertising-postcard" type="tns:Advertising-postcard" substitutionGroup="tns:postcard"/>
</schema>

=== pilipeikoko/XmlParser/src/main/resources/data/oldCards.xml
<?xml version="1.0" encoding="UTF-8" ?>
<old-cards
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="https://github.com/pilipeikoko/XmlParser"
        xsi:schemaLocation="https://github.com/pilipeikoko/XmlParser ./oldCards.xsd">

    <postcard postcard-id="id1">
        <theme>theme0</theme>
        <is-sent>true</is-sent>
        <country>BELARUS</country>
        <release-date>2021-12-12</release-date>
        <author>None</author>
        <valuation>HISTORICAL</valuation>
    </postcard>


    <postcard postcard-id="id2">
        <theme>Hello</theme>
        <is-sent>true</is-sent>
        <country>RUSSIA</country>
        <release-date>2020-12-12</release-date>
        <author>Nonex2</author>
        <valuation>HISTORICAL</valuation>
    </postcard>

    <advertising-postcard postcard-id="id3">
        <theme>Bye</theme>
        <is-sent>true</is-sent>
        <country>LATVIA</country>
        <release-date>2022-12-10</release-date>
        <author>Lermontov</author>
        <valuation>THEMATIC</valuation>
        <company>Unknown</company>
        <expiration-date>2020-12-13</expiration-date>
    </advertising-postcard>

    <congratulatory-postcard postcard-id="id4">
        <theme>Merry christmas</theme>
        <is-sent>true</is-sent>
        <country>LITHUANIA</country>
        <release-date>2020-11-11</release-date>
        <author>None</author>
        <valuation>THEMATIC</valuation>
        <holiday>Christmas</holiday>
    </congratulatory-postcard>

    <advertising-postcard postcard-id="id5" postcard-website="www.random.org">
        <theme>theme2</theme>
        <is-sent>true</is-sent>
        <country>UKRAIN</country>
        <release-date>2019-12-10</release-date>
        <author>RandomAuthor1</author>
        <valuation>HISTORICAL</valuation>
        <company>EPAM</company>
        <expiration-date>2023-12-13</expiration-date>
    </advertising-postcard>

    <advertising-postcard postcard-id="id6">
        <theme>theme3</theme>
        <is-sent>false</is-sent>
        <country>RUSSIA</country>
        <release-date>2021-11-10</release-date>
        <author>Pavlov</author>
        <valuation>HISTORICAL</valuation>
        <company>bsuir</company>
        <expiration-date>2023-08-13</expiration-date>
    </advertising-postcard>

    <postcard postcard-id="id7">
        <theme>theme4</theme>
        <is-sent>false</is-sent>
        <country>RUSSIA</country>
        <release-date>2018-12-12</release-date>
        <author>Ivanov</author>
        <valuation>COLLECTIBLE</valuation>
    </postcard>

    <postcard postcard-id="id8">
        <theme>theme5</theme>
        <is-sent>true</is-sent>
        <country>RUSSIA</country>
        <release-date>2014-12-12</release-date>
        <author>Petrov</author>
        <valuation>HISTORICAL</valuation>
    </postcard>

    <advertising-postcard postcard-id="id9">
        <theme>theme6</theme>
        <is-sent>false</is-sent>
        <country>LATVIA</country>
        <release-date>2010-11-10</release-date>
        <author>Sidorov</author>
        <valuation>COLLECTIBLE</valuation>
        <company>bsu</company>
        <expiration-date>2020-08-13</expiration-date>
    </advertising-postcard>

    <postcard postcard-id="id10">
        <theme>theme7</theme>
        <is-sent>false</is-sent>
        <country>LITHUANIA</country>
        <release-date>2013-12-12</release-date>
        <author>Monin</author>
        <valuation>COLLECTIBLE</valuation>
    </postcard>

    <advertising-postcard postcard-id="id11">
        <theme>theme8</theme>
        <is-sent>true</is-sent>
        <country>RUSSIA</country>
        <release-date>2015-11-10</release-date>
        <author>Vomin</author>
        <valuation>HISTORICAL</valuation>
        <company>epam</company>
        <expiration-date>2016-08-13</expiration-date>
    </advertising-postcard>

    <congratulatory-postcard postcard-id="id12">
        <theme>Happy new year</theme>
        <is-sent>false</is-sent>
        <country>POLAND</country>
        <release-date>2010-11-11</release-date>
        <author>Totti</author>
        <valuation>THEMATIC</valuation>
        <holiday>New year</holiday>
    </congratulatory-postcard>

    <congratulatory-postcard postcard-id="id13">
        <theme>Happy birthday</theme>
        <is-sent>true</is-sent>
        <country>BELARUS</country>
        <release-date>2010-11-11</release-date>
        <author>Matic</author>
        <valuation>HISTORICAL</valuation>
        <holiday>Birthday</holiday>
    </congratulatory-postcard>

    <postcard postcard-id="id14">
        <theme>theme9</theme>
        <is-sent>true</is-sent>
        <country>RUSSIA</country>
        <release-date>2012-12-12</release-date>
        <author>Mojin</author>
        <valuation>HISTORICAL</valuation>
    </postcard>

    <congratulatory-postcard postcard-id="id15">
        <theme>Merry christmas</theme>
        <is-sent>true</is-sent>
        <country>RUSSIA</country>
        <release-date>2006-11-11</release-date>
        <author>Sovin</author>
        <valuation>THEMATIC</valuation>
        <holiday>Christmas</holiday>
    </congratulatory-postcard>

    <advertising-postcard postcard-id="id16">
        <theme>theme10</theme>
        <is-sent>true</is-sent>
        <country>BELARUS</country>
        <release-date>2006-11-10</release-date>
        <author>Merrin</author>
        <valuation>COLLECTIBLE</valuation>
        <company>epam</company>
        <expiration-date>2016-08-13</expiration-date>
    </advertising-postcard>

</old-cards>
